### PR TITLE
Add support for unit testing

### PR DESCRIPTION
**Pull request by Pezmc**
Added by vue cli using `vue add unit-jest` and manually tweaked.

### CODE REVIEW

**Comment by Pezmc** [comment]
The lint action is failing as there are no files in `tests/` yet, I can either undo that change, or merge with the failure as it'll be fixed once #80 is merged.

**Review by knolleary — APPROVED** [review]
Given everything is passing cleanly in #80 I'm happy for this PR to move forward as-is

**Comment by Steve-Mcl** [comment]
@Pezmc 

I realise this is merged but having just pulled it down to my dev env, I see the linting fails on `.eslintrc` 

image

I am wondering if this is related to what we spoke about before regarding different environments? or an issue with my env picking up `.eslintrc` as `jsonc` ?

**Comment by Pezmc** [comment]
@Steve-Mcl Should be resolved. FWIW it looks like that's your local editor deciding to run our eslint rules, but against all files, while the `npm lint` task used on CI only checks `src/,tests/`. Neither option is more correct than the other. There's definitely a wider discussion to be had as to whether CI should lint against all files or not.

**Pull request merged**
