### PR TITLE
Adds new "Toggle Switch" Component

### LINKED ISSUE #150: Toggle Switch
### Description

per: https://vuetifyjs.com/en/components/switches/

multiple scenarios popping up where a toggle switch, with customisable icon state would be very beneficial. Really like the new one in Figma for enabling developer mode, which we could replicate for our own Device "Developer Mode"

Screenshot 2023-07-11 at 17 19 22

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Adds new toggle switch
- Include `disabled`, `icon` slot and light & dark theme styling
- Loading state & async mode

### Sync Mode (Default)

https://github.com/flowforge/forge-ui-components/assets/99246719/c5c0e179-b2aa-4ed5-a0aa-86c62af8b360

### Async Mode:

https://github.com/flowforge/forge-ui-components/assets/99246719/9f6742a6-b117-47f6-a1bc-df77c5c989bf

## Related Issue(s)

Closes #150

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by joepavitt** [comment]
@Steve-Mcl just uploaded video above of the async working - let me know what you think.

**Comment by Steve-Mcl** [comment]
Very nice actually.

Might be worth mentioning on the demo page that implementers ensure loading flag is reset in ALL eventualities otherwise they wont get a second shot of the button without a refresh (i.e. wrap requests in try/finally and ensure the loading flag is cleared)

**Comment by joepavitt** [comment]
@Pezmc this is now ready for review

**Review by Pezmc — APPROVED** [review]

**Comment by knolleary** [comment]
Whilst this does build locally, when I try to rebuild the forge app with the `main` branch of ui-components, I get the following error:

```
ERROR in ../forge-ui-components/dist/forge-ui-components.js 7:16-51
Module not found: Error: Can't resolve '@/components/Spinner.vue' in '/Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/dist'
resolve '@/components/Spinner.vue' in '/Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/dist'
  Parsed request is a module
  using description file: /Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/dist/node_modules doesn't exist or is not a directory
      looking for modules in /Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/node_modules
        /Users/nol/code/ff/flowforge-dev-env/packages/forge-ui-components/node_modules/@/components doesn't exist
      /Users/nol/code/ff/flowforge-dev-env/packages/node_modules doesn't exist or is not a directory
      looking for modules in /Users/nol/code/ff/flowforge-dev-env/node_modules
        /Users/nol/code/ff/flowforge-dev-env/node_modules/@/components doesn't exist
      /Users/nol/code/ff/node_modules doesn't exist or is not a directory
      /Users/nol/code/node_modules doesn't exist or is not a directory
      /Users/nol/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./frontend/src/main.js 2:0-63 12:31-48
```

I pulled main, ran `npm install` and `npm run build`

**Pull request merged**
