### PR TITLE
flowforge-ui-components -> forge-ui-components

### PR DESCRIPTION
**Pull request by joepavitt**

### CODE REVIEW

**Comment by knolleary** [comment]
Looks good - although some old references in the README to update as well.

**Comment by knolleary** [comment]
Great - I assume you'll rebuild the `gh-docs` stuff manually given the changed repo name etc?

**Comment by joepavitt** [comment]
@knolleary good q - not entirely sure what the process is for that. Was my first time working with subtrees. Is there a nicer way to automate that process?

**Comment by knolleary** [comment]
You can setup a github action to build and push back to the `gh-pages` branch. Here's the one we use for the main website - https://github.com/flowforge/website/blob/main/.github/workflows/build.yml

**Pull request merged**
