### PR TITLE
Upgrade eslint vue and swap to vue3-strongly-recommended

### PR DESCRIPTION
**Pull request by Pezmc**
Currently linting of components is using the preset `plugin:vue/vue3-essential` from [`eslint-plugin-vue`](https://eslint.vuejs.org/user-guide/#usage).

However, the ruleset `plugin:vue/vue3-strongly-recommended` also includes some [valuable rules](https://eslint.vuejs.org/rules/#priority-b-strongly-recommended-improving-readability) based on the [Vue.js style guide](https://vuejs.org/style-guide/rules-strongly-recommended.html) that can help the components stay consistent, ensure all properties are declared and improve readability.

To that end this PR:

- Enables `plugin:vue/vue3-strongly-recommended`
- Disables style-related rules in the config that need excessive code changes
- Temporarily disables style-related rules in the config that can be auto-fixed without many changes
- Adds the `eslint-disable` directive on rules that should be addressed (follow up PR)
- Additionally drops the `@vue/cli-plugin-eslint` dependency since it's not used

### CODE REVIEW

**Comment by joepavitt** [comment]
Noticing a lot of exceptions then added into the existing code base around `props` - is the plan ere to fix all of those eventually? If not, then why not had a global exception in the config?

**Comment by Pezmc** [comment]
Yes, the convention as I understand it, is that if it's disabled in a comment that usually means it _should_ be fixed, whereas a global exception is saying, we disagree with this rule.

Having said that, all of the exceptions are fixed and removed in a follow-up PR: https://github.com/flowforge/forge-ui-components/pull/78

**Comment by joepavitt** [comment]
@Pezmc can you just double check and resolve the conflicts please?

**Comment by Pezmc** [comment]
@joepavitt Rebased and resolved.

**Comment by joepavitt** [comment]
@Pezmc and the linting error about an empty `/tests` folder?

**Comment by Pezmc** [comment]
Should resolve now https://github.com/flowforge/forge-ui-components/pull/80 is merged (same as #81).

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
